name: iOS

on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 45

    env:
      DEVELOPER_DIR: /Applications/Xcode_13.1.app

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Node
      uses: actions/setup-node@v3

    - name: Install node_modules
      run: |
        npm install

    - name: Pod Install
      run: |
        cd ios && pod install && cd ..

    - name: Install Applesimutils
      run: |
        brew tap wix/brew
        brew install applesimutils

    - name: Build App Detox
      run: |
        npx detox build -c ios

    - name: Run Detox tests
      run: |
        npx detox test -c ios